### ISSUE TITLE
bot goes to sleep

### ISSUE THREAD

**Issue by rejon** [QiHardware/scale-telegram-bot#2]
- how to wake him up needs to be automated OR
- make it clear with a link or something in the chat channel how to wake him

**Comment by rejon** [comment]
Go to this link right? https://trite-foundation.glitch.me/links

**Comment by clemsos** [comment]
Yes

**Comment by clemsos** [comment]
Heroku is way to go https://www.heroku.com/pricing

**Comment by clemsos** [comment]
ok works here https://scale-bot-staging.herokuapp.com/links but not link to the bot yet. The problem being that you can not store file in Heroku so db is currently erased at each restart... need to setup a database. Why do we need servers again?

**Comment by rejon** [comment]
Yeah? how about fabricatorz.org <http://fabricatorz.org/> server

**Comment by rejon** [comment]
Did you talk to @barrythrew about this?

Jon

**Comment by clemsos** [comment]
ok deployed elsewhere so shouldnt sleep.  There is still a hack in ad2e239 to get https but closing for now as this is just a server issue, not code

**Comment by rejon** [comment]
Where deployed?
